{"name": "Ошибка при повторном использовании логина для создания курьера", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 409, got 201. Response: {\"ok\":true}\nassert 201 == 409\n +  where 201 = <Response [201]>.status_code", "trace": "self = <test_courier_create.TestCourierCreate object at 0x000002760553C650>\n\n    @allure.title('Ошибка при повторном использовании логина для создания курьера')\n    @allure.description('Код и тело ответа.')\n    def test_create_courier_account_login_taken_conflict(self):\n        payload = {\n            'login': Data.valid_login,\n            'password': create_random_password(),\n            'firstName': create_random_firstname()\n        }\n        response = requests.post(Urls.URL_courier_create, json=payload)\n>       assert response.status_code == 409, f\"Expected 409, got {response.status_code}. Response: {response.text}\"\nE       AssertionError: Expected 409, got 201. Response: {\"ok\":true}\nE       assert 201 == 409\nE        +  where 201 = <Response [201]>.status_code\n\ntests\\test_courier_create.py:32: AssertionError"}, "description": "Код и тело ответа.", "start": 1742320156260, "stop": 1742320156347, "uuid": "1fc2aacf-7fd4-44ae-844d-36e14116004e", "historyId": "6f67603245d03577c0bb7ad6998f5f65", "testCaseId": "6f67603245d03577c0bb7ad6998f5f65", "fullName": "tests.test_courier_create.TestCourierCreate#test_create_courier_account_login_taken_conflict", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_create"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "DESKTOP-JHHR6FB"}, {"name": "thread", "value": "1556-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_create"}]}